version: "3.7"

networks:
  net:
    attachable: true
    name: net

volumes:
  pg_data:

x-defaults:
  &defaults
  restart: ${RESTART:-always}
  networks:
    net:
  logging:
    driver: json-file
    options:
      max-file: '5'
      max-size: 20m

services:
  bookstore:
    <<: *defaults
    image: bookstore:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"

  postgres:
    <<: *defaults
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
