package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/ountyrio/gql-bookstore/internal/common"
	"github.com/ountyrio/gql-bookstore/internal/graph/generated"
	gqlmodel "github.com/ountyrio/gql-bookstore/internal/graph/model"
	"github.com/ountyrio/gql-bookstore/internal/types"
)

// Get is the resolver for the get field.
func (r *authorsQueryNSResolver) Get(ctx context.Context, obj *gqlmodel.AuthorsQueryNs, id int) (*gqlmodel.Author, error) {
	query := &types.AuthorIDRequestDto{
		ID: id,
	}

	author, err := r.authorService.GetById(ctx, query)

	if err != nil {
		return nil, err
	}

	res := CastAuthorDtoToGql(&author.Author)
	return res, nil
}

// Query is the resolver for the query field.
func (r *authorsQueryNSResolver) Query(ctx context.Context, obj *gqlmodel.AuthorsQueryNs, filter *gqlmodel.AuthorsQueryNsQueryFilterInput) (*gqlmodel.AuthorsQueryNsQueryResult, error) {
	query := &types.AuthorQueryRequestDto{}

	if filter.Pagination != nil {
		if filter.Pagination.Page != nil {
			query.Page = *filter.Pagination.Page

			if query.Page < 1 {
				query.Page = 1
			}
		}
		if filter.Pagination.Limit != nil {
			query.Limit = *filter.Pagination.Limit

			if query.Limit < 1 {
				query.Limit = 1
			}
		}
	}

	if filter.Sort != nil {
		if filter.Sort.Field != nil {
			query.Field = *filter.Sort.Field
			if query.Field == "" {
				query.Field = "Lastname"
			}
		}

		if filter.Sort.Order != nil {
			query.Order = *filter.Sort.Order
			if query.Order == "" {
				query.Order = "ASC"
			}
		}
	}
	authors, err := r.authorService.Query(ctx, query)

	if err != nil {
		return nil, err
	}

	ptr := int(authors.Count)

	return &gqlmodel.AuthorsQueryNsQueryResult{
		Authors: common.SliceMapPtr(CastAuthorDtoToGql, authors.Authors),
		Count:   &ptr,
	}, nil
}

// AuthorsQueryNS returns generated.AuthorsQueryNSResolver implementation.
func (r *Resolver) AuthorsQueryNS() generated.AuthorsQueryNSResolver {
	return &authorsQueryNSResolver{r}
}

type authorsQueryNSResolver struct{ *Resolver }
