package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/ountyrio/gql-bookstore/internal/common"
	"github.com/ountyrio/gql-bookstore/internal/graph/generated"
	gqlmodel "github.com/ountyrio/gql-bookstore/internal/graph/model"
	"github.com/ountyrio/gql-bookstore/internal/types"
)

// Get is the resolver for the get field.
func (r *genresQueryNSResolver) Get(ctx context.Context, obj *gqlmodel.GenresQueryNs, id int) (*gqlmodel.Genre, error) {
	query := &types.GenreIDRequestDto{
		ID: id,
	}

	genre, err := r.genreService.GetById(ctx, query)

	if err != nil {
		return nil, err
	}
	res := CastGenreDtoToGql(&genre.Genre)
	return res, nil
}

// Query is the resolver for the query field.
func (r *genresQueryNSResolver) Query(ctx context.Context, obj *gqlmodel.GenresQueryNs, filter *gqlmodel.GenresQueryNsQueryFilterInput) (*gqlmodel.GenresQueryNsQueryResult, error) {
	query := &types.GenreQueryRequestDto{}

	if filter.Pagination != nil {
		if filter.Pagination.Page != nil {
			query.Page = *filter.Pagination.Page

			if query.Page < 1 {
				query.Page = 1
			}
		}
		if filter.Pagination.Limit != nil {
			query.Limit = *filter.Pagination.Limit

			if query.Limit < 1 {
				query.Limit = 1
			}
		}
	}

	if filter.Sort != nil {
		if filter.Sort.Field != nil {
			query.Field = *filter.Sort.Field
			if query.Field == "" {
				query.Field = "Name"
			}
		}

		if filter.Sort.Order != nil {
			query.Order = *filter.Sort.Order
			if query.Order == "" {
				query.Order = "ASC"
			}
		}
	}
	genres, err := r.genreService.Query(ctx, query)

	if err != nil {
		return nil, err
	}

	ptr := int(genres.Count)

	return &gqlmodel.GenresQueryNsQueryResult{
		Genres: common.SliceMapPtr(CastGenreDtoToGql, genres.Genres),
		Count:  &ptr,
	}, nil
}

// GenresQueryNS returns generated.GenresQueryNSResolver implementation.
func (r *Resolver) GenresQueryNS() generated.GenresQueryNSResolver { return &genresQueryNSResolver{r} }

type genresQueryNSResolver struct{ *Resolver }
