package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/ountyrio/gql-bookstore/internal/graph/generated"
	gqlmodel "github.com/ountyrio/gql-bookstore/internal/graph/model"
)

// Authors is the resolver for the authors field.
func (r *mutationResolver) Authors(ctx context.Context) (*gqlmodel.AuthorsMutationNs, error) {
	return &gqlmodel.AuthorsMutationNs{}, nil
}

// Books is the resolver for the books field.
func (r *mutationResolver) Books(ctx context.Context) (*gqlmodel.BooksMutationNs, error) {
	return &gqlmodel.BooksMutationNs{}, nil
}

// Genres is the resolver for the genres field.
func (r *mutationResolver) Genres(ctx context.Context) (*gqlmodel.GenresMutationNs, error) {
	return &gqlmodel.GenresMutationNs{}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
